# Generated by Django 5.0.2 on 2024-02-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('is_default', models.BooleanField(default=True)),
            ],
        ),
    ]
